# Sinker configurations (for cleanup)
sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 30m


# All the Tide configurations
tide:
  queries:
  - orgs:
    - sanster23
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase


# Default Labels template for jobs
job_labels_template: &job_labels_template
  preset-dind-enabled: "true"

periodics:
- interval: 30m
  agent: kubernetes
  name: echo-test
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]

# Presubmit jobs
presubmits:
  sanster23/k8s_prow_flask_cicd:
  - name: workflow-test-presubmit
    always_run: true               # Run for every PR, or only when requested.
    skip_report: false             # Whether to skip setting a status on GitHub.
    trigger: "(?m)^/test workflow"
    rerun_command: "/test workflow"
    context: workflow-test-presubmit
    agent: kubernetes
    max_concurrency: 10
    labels:
      <<: *job_labels_template
      preset-build-pr: "true"
    spec:
      serviceAccountName: "default"
      containers:
      - image: docker.io/shekhawatsanjay/prow-ci-test
        args:
        - "pre"
        securityContext:
          privileged: true
        env:
        - name: workflow_chart
          value: testing_workflow
  - name: prow-test-presubmit
    always_run: true               # Run for every PR, or only when requested.
    skip_report: false             # Whether to skip setting a status on GitHub.
    trigger: "(?m)^/test prow"
    rerun_command: "/test prow"
    context: prow-test-presubmit
    agent: kubernetes
    max_concurrency: 10
    labels:
      <<: *job_labels_template
      preset-build-pr: "true"
    spec:
      serviceAccountName: "default"
      containers:
      - image: docker.io/shekhawatsanjay/prow-ci-test:prow
        args:
        - "pre"
        securityContext:
          privileged: true

# Postsubmit jobs
postsubmits:
  sanster23/k8s_prow_flask_cicd:
  - name: test-postsubmit
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
    max_concurrency: 10   # Run no more than this number concurrently.
    branches:             # Only run against these branches.
    - master
  - name: release-postsubmit
    agent: kubernetes
    max_concurrency: 10   # Run no more than this number concurrently.
    skip_report: false             # Whether to skip setting a status on GitHub.
    labels:
      <<: *job_labels_template
      preset-build-master: "true"
    spec:
      serviceAccountName: "default"
      containers:
      - image: docker.io/shekhawatsanjay/prow-ci-test
        args:
        - "pre"
        securityContext:
          privileged: true
