presubmits:
  sanster23/k8s_prow_flask_cicd:
  - name: unit-tests
    always_run: true
    skip_report: false
    context: unit-tests
    trigger: "(?m)^/test this"
    rerun_command: "/test this"
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command:
        - printenv
    max_concurrency: 10
    branches:
    - master
