apiVersion: v1
kind: ServiceAccount
metadata:
  name: prow
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prow
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "secrets", "configmaps", "events"]
  verbs: ["*"]
- apiGroups: ["prow.k8s.io"]
  resources: ["prowjobs"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prow
subjects:
- kind: ServiceAccount
  name: prow
  namespace: default

