# Presets
presets:
  - labels:
      preset-dind-enabled: "true"
    env:
    - name: DOCKER_IN_DOCKER_ENABLED
      value: "true"
  - labels:
      preset-docker-credentials: "true"
    env:
    - name: DOCKER_USER
      valueFrom:
        secretKeyRef:
          name: docker-creds
          key: user
    env:
    - name: DOCKER_PASS
      valueFrom:
        secretKeyRef:
          name: docker-creds
          key: password      

# Sinker configurations (for cleanup)
sinker:
  resync_period: 1m
  max_prowjob_age: 4h
  max_pod_age: 4h


# All the Tide configurations
tide:
  queries:
  - orgs:
    - sanster23
  - repos:
    - sanster23/k8s-prow-guide
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase

deck:
  spyglass:
    size_limit: 500e+6 # 500MB
    viewers:
      "started.json|finished.json":
      - "metadata"
      "build-log.txt":
      - "buildlog"
      "artifacts/junit.*\\.xml":
      - "junit"
  tide_update_period: 1s

# Plank configurations
plank:
  allow_cancellations: true # whether to delete ProwJobs' pod (true) or not (false) when new instances are triggered for the same PR
  # used to link to job results for decorated jobs (with pod utilities)
  job_url_template: 'http://192.168.99.100:32710/view/gcs/triliok8s/{{if eq .Spec.Type "presubmit"}}pr-logs/pull{{else if eq .Spec.Type "batch"}}pr-logs/pull{{else}}logs{{end}}{{if .Spec.Refs}}{{if ne .Spec.Refs.Org ""}}/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}{{end}}{{end}}{{if eq .Spec.Type "presubmit"}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'
  job_url_prefix: 'http://192.168.99.100:32710/view/gcs/'
  default_decoration_config:
    utility_images: # pull specs for container images used to construct job pods
      clonerefs: gcr.io/k8s-prow/clonerefs:v20190221-d14461a
      initupload: gcr.io/k8s-prow/initupload:v20190221-d14461a
      entrypoint: gcr.io/k8s-prow/entrypoint:v20190221-d14461a
      sidecar: gcr.io/k8s-prow/sidecar:v20190221-d14461a
    gcs_configuration: # configuration for uploading job results to GCS
      bucket: triliok8s
      path_strategy: explicit # or `legacy`, `single`
    gcs_credentials_secret: gcs-sa
