# --- Prow Presets ---
presets:
  - labels:
      preset-dind-enabled: "true"
    env:
      - name: DOCKER_IN_DOCKER_ENABLED
        value: "true"
  - labels:
      preset-docker-credentials: "true"
    env:
      - name: DOCKER_USER
        valueFrom:
          secretKeyRef:
            name: docker-creds
            key: user
      - name: DOCKER_PASS
        valueFrom:
          secretKeyRef:
            name: docker-creds
            key: password

# --- Sinker (ProwJob/Pod Cleanup) ---
sinker:
  resync_period: 1m
  max_prowjob_age: 4h
  max_pod_age: 4h

# --- Tide (GitHub PR Merge Automation) ---
tide:
  queries:
    - orgs:
        - KiranItagi666
    - repos:
        - KiranItagi666/k8s-prow-guide
      labels:
        - lgtm
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase

# --- Deck (Prow UI) ---
deck:
  spyglass:
    size_limit: 500000000
    viewers:
      "started.json|finished.json":
        - metadata
      "build-log.txt":
        - buildlog
      "artifacts/junit.*\\.xml":
        - junit
  tide_update_period: 1s

# --- Plank (Job Scheduler/Controller) --
plank:
  allow_cancellations: true
  max_concurrency: 50
  job_url_template: 'http://43.204.32.130:32710/view/{{.Spec.Job}}/{{.Status.BuildID}}/'
  job_url_prefix:   'http://43.204.32.130:32710/view/'
  default_decoration_config:
    timeout: 7200000000000
    grace_period: 600000000000
    utility_images:
      clonerefs:  gcr.io/k8s-prow/clonerefs:v20190312-abfe0e0
      initupload: gcr.io/k8s-prow/initupload:v20190312-abfe0e0
      entrypoint: gcr.io/k8s-prow/entrypoint:v20190312-abfe0e0
      sidecar:    gcr.io/k8s-prow/sidecar:v20190312-abfe0e0
    gcs_configuration:
      bucket: "fake-bucket"
      path_strategy: "legacy"
      default_org: "fake-org"
      default_repo: "fake-repo"
    gcs_credentials_secret: gcs-credentials

